#!/usr/bin/env bash

version="$1"
IFS=. read -r major minor build <<< "$version"

sed -i  's/\(#define VENTHOOD_VERSION_MAJOR\).*/\1 '$major'/' venthoodSrc/app.ino
sed -i  's/\(#define VENTHOOD_VERSION_MINOR\).*/\1 '$minor'/' venthoodSrc/app.ino
sed -i  's/\(#define VENTHOOD_VERSION_PATCH\).*/\1 '$build'/' venthoodSrc/app.ino
#sed -i '' 's/version-.*-green.svg/version-'$version'-green.svg/g' README.md
